
function referenceTable()	
       
{tableModel=''
	
	
	tableModel+=' <h4><center><b>HALL COEFFICIENTS </b></center><h4>  '          
		+'<table class="table  table-bordered table-hover">'
		+' <thead>'
		+'  <tr class="tableHeader">'
		+'    <th>Material</th>'
		+'     <th>Flux density <br>Wb /m<sup>2</sup></th>'
		+'      <th> Temperature &deg;C</th>'
		+'      <th> KH (V - M) /A.Wb - m<sup>-2</sup></th>'
		+' </tr>'
		+' </thead>'
		+'<tbody>'
		+' <tr>'
		+'  <td>As</td>'
		+'  <td> 0.4 to 0.8</td>'
		+' <td>20</td>'
		+' <td>4.52 &times;10 <sup>-9</sup> </td>'
		+' </tr>'
		+'  <tr>'
		+'    <td>Bi</td>'
		+'    <td>0.113</td>'
		+'    <td>20</td>'
		+'     <td>-1&times;10<sup>-6</sup></td>'
		+'</tr>'
		+' <tr>'
		+'  <td>C</td>'
		+'  <td>0.4 to 1.8</td>'
		+'  <td>30</td>'
		+'   <td>-11.73&times;10<sup >-9</sup></td>'
		+' </tr>'
		+' <tr>'
		+'  <td>Cu</td>'
		+' <td> 0.8 to 2.2</td>'
		+'  <td>20</td>'
		+'   <td>-52&times;10<sup >-12</sup></td>'
		+' </tr>'
		+' <tr>'
		+'   <td>Fe</td>'
		+'   <td>1.7</td>'
		+'   <td>25</td>'
		+' <td>1.1&times;10<sup >-9</sup></td>'
		+' </tr>'
		+' <tr>'
		+' <td>Ge</td>'
		+'  <td>0.001-0.8</td>'
		+' <td>25</td>'
		+' <td>-8&times;10<sup >-3</sup></td>'
		+' </tr>'
		+' <tr>'
		+'  <td>Si</td>'
		+' <td>2</td>'
		+' <td>25</td>'
		+'   <td>4.1&times;10<sup>-6</sup></td>'
		+' </tr>'
		+' <tr>'
		+'   <td>Sn</td>'
		+'  <td>0.4</td>'
		+'  <td>25</td>'
		+'   <td>-2&times;10<sup>-12</sup></td>'
		+' </tr>'
		+' <tr>'
		+'   <td>Te</td>'
		+' <td>0.3-0.9</td>'
		+' <td>20</td>'
		+'  <td> 53&times;10<sup  >-6</sup></td>'
		+' </tr>'
		+' </tbody>'
		+'</table>'
	
	  $("#tableModel").html(tableModel); 


		
}